services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: yuuke
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d yuuke"]
      interval: 5s
      timeout: 5s
      retries: 5
  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    entrypoint: ["migrate", "-source", "file://./migrations", "-database", "postgres://postgres:1@db:5432/yuuke?sslmode=disable", "up"]
    depends_on:
      db:
        condition: service_healthy

  app:
    image: ghcr.io/abipasundan/koda-b6-backend:latest
    container_name: express_app
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
      - PGHOST=db
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=1
      - PGSSLMODE=disable
      - PGDATABASE=yuuke
      - APP_SECRET=d8e8fca2dc0f896fd7cb4cb0031ba249
    depends_on:
      - db

volumes:
  pgdata: